[package]
authors = ["Jonathan Morley <morley.jonathan@gmail.com>"]
description = "Generates temporary AWS credentials with Okta."
edition = "2018"
name = "oktaws"
version = "0.14.1"
[dependencies]
anyhow = "*"
async-recursion = "*"
base64 = "0.13"
clap = "3.0.0-beta.2"
dialoguer = "0.8"
dirs = "3"
futures = "*"
glob = "0.3"
itertools = "0.10"
kuchiki = "0.8"
log = "0.4"
path_abs = "0.5"
paw = "*"
pretty_env_logger = "0.4"
regex = "1"
samuel = "*"
serde_ini = "0.2"
thiserror = "*"
username = "0.2"
walkdir = "2"

[dependencies.backoff]
features = ["tokio"]
version = "*"

[dependencies.indexmap]
features = ["serde-1"]
version = "1.0"

[dependencies.reqwest]
default_features = false
features = ["cookies", "json", "rustls-tls"]
version = "0.11"

[dependencies.rusoto_core]
default_features = false
features = ["rustls", "rustls-webpki"]
version = "0.47"

[dependencies.rusoto_credential]
version = "0.47"

[dependencies.rusoto_iam]
default_features = false
features = ["rustls"]
version = "0.47"

[dependencies.rusoto_sts]
default_features = false
features = ["rustls"]
version = "0.47"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.structopt]
features = ["paw"]
version = "0.3"

[dependencies.tokio]
features = ["full"]
version = "1"

[dependencies.toml]
version = "0.5.8"

[dependencies.url]
features = ["serde"]
version = "2.1"

[dev-dependencies]
serial_test = "0.5"
tempfile = "3"

[target]
[target."cfg(not(target_os = \"linux\"))"]
[target."cfg(not(target_os = \"linux\"))".dependencies]
keyring = "0.10"
